<a href="https://colab.research.google.com/github/Sang897/data-analytics-projects/blob/master/Predicting_Breast_Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [28]:
#The following data is based on https://www.kaggle.com/code/buddhiniw/breast-cancer-prediction/data

#From here.
dataset = pd.read_csv('breastcancerprediction.csv')

In [30]:
type(dataset)

pandas.core.frame.DataFrame

In [31]:
for col in dataset.columns:
  print(col)

id
diagnosis
radius_mean
texture_mean
perimeter_mean
area_mean
smoothness_mean
compactness_mean
concavity_mean
concave points_mean
symmetry_mean
fractal_dimension_mean
radius_se
texture_se
perimeter_se
area_se
smoothness_se
compactness_se
concavity_se
concave points_se
symmetry_se
fractal_dimension_se
radius_worst
texture_worst
perimeter_worst
area_worst
smoothness_worst
compactness_worst
concavity_worst
concave points_worst
symmetry_worst
fractal_dimension_worst


In [32]:
dataset= dataset.drop(dataset.columns[[-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1]], axis=1) #Drop the columns that says "worst" which are indexes -11 to -1 (-11:-1)

In [33]:
for col in dataset.columns:
  print(col)

id
diagnosis
radius_mean
texture_mean
perimeter_mean
area_mean
smoothness_mean
compactness_mean
concavity_mean
concave points_mean
symmetry_mean
fractal_dimension_mean
radius_se
texture_se
perimeter_se
area_se
smoothness_se
compactness_se
concavity_se
concave points_se
symmetry_se


In [ ]:
  #For the columns that says "worst", take it out. 

In [34]:
Inputvariable = dataset.iloc[:,2:-1].values

In [36]:
Outputvariable= dataset.iloc[:, 1].values

#using dataset.iloc squarebracket, semilcolon, 1. values 

In [37]:
print(Inputvariable)
print(Outputvariable)

[[1.799e+01 1.038e+01 1.228e+02 ... 4.904e-02 5.373e-02 1.587e-02]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.308e-02 1.860e-02 1.340e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 4.006e-02 3.832e-02 2.058e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 3.731e-02 4.730e-02 1.557e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 6.158e-02 7.117e-02 1.664e-02]
 [7.760e+00 2.454e+01 4.792e+01 ... 4.660e-03 0.000e+00 0.000e+00]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B'

In [38]:
#Encoding dignosis result 
from sklearn.preprocessing import LabelEncoder #Imports to perform one hot encoding 
Encoder = LabelEncoder()
Outputvariable = Encoder.fit_transform(Outputvariable) #colon 

#Performing encoding. 

#Encoding categorical data has two types: 
#Label Encoding: Gender column => binary result with relationships. 
#One hot encoding => multiple results with no particular relationships. 


In [39]:
Outputvariable

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
Outputvariable #M and B converted into 0s and 1s for computations

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [40]:
#Make training and testing set. 
from sklearn.model_selection import train_test_split
inputvaraible_train, inputvaraible_test, outputvaraible_train, outputvariable_test = train_test_split(Inputvariable, Outputvariable, test_size = 0.3, random_state = 0)

In [41]:
#apply the feature scaling. For testing set, apply transform() and for train_set apply fit_transform 
from sklearn.preprocessing import StandardScaler
Standardscaler = StandardScaler()
inputvariable_train = Standardscaler.fit_transform(inputvaraible_train)
inputvariable_test = Standardscaler.transform(inputvaraible_test) #avoid information lickaage. 

#This step is the end of data preprpocessing. 

In [ ]:
inputvariable_test

array([[-0.21855296,  0.31710749, -0.14938447, ..., -0.14567981,
         0.11542304,  0.28378104],
       [-0.27141746,  1.44727832, -0.33290634, ..., -1.01213192,
        -0.56501333, -0.89282925],
       [-0.04604776, -0.84412512, -0.11098232, ..., -0.94337721,
        -0.77128156, -0.15687139],
       ...,
       [-0.13230036, -0.12253613, -0.14574637, ..., -0.1540065 ,
        -0.36319493,  0.31452423],
       [-0.24637638,  0.56799108, -0.28682376, ..., -0.27652787,
        -0.46515527, -0.90171062],
       [-1.35013142,  0.65639767, -1.34712739, ..., -0.40202307,
         0.30602931,  0.19496737]])

In [42]:
#Launch ANN Model
ArtificalNeuralNetworkModel = tf.keras.models.Sequential()

In [ ]:
#Add the input layer and hidden layer.
ArtificalNeuralNetworkModel.add(tf.keras.layers.Dense(10, activation='relu'))
#this is using the rectifier function 
#add methods can add any new layer. And keep the parameters as 10. 
#Adds the second layer. 

ArtificalNeuralNetworkModel.add(tf.keras.layers.Dense(10, activation='relu'))

ArtificalNeuralNetworkModel.add(tf.keras.layers.Dense(1, activation='sigmoid'))
#What's the reason that we need just 1? #That's for binary output 


In [ ]:
ArtificalNeuralNetworkModel.compile(      
optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#if non binary, then then categorical_crossentropy 


In [ ]:
ArtificalNeuralNetworkModel.fit(inputvaraible_train, outputvaraible_train, batch_size = 32, epochs = 100)

#batch size= using several predictions and we are using 100 predictions. And the accuracy gets better and better.

Epoch 1/100
13/13 [==============================] - 1s 3ms/step - loss: 17.0166 - accuracy: 0.3744
Epoch 2/100
13/13 [==============================] - 0s 3ms/step - loss: 8.1047 - accuracy: 0.3744
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 1.5084 - accuracy: 0.5678
Epoch 4/100
13/13 [==============================] - 0s 3ms/step - loss: 0.8607 - accuracy: 0.6482
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5807 - accuracy: 0.6709
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4589 - accuracy: 0.8216
Epoch 7/100
13/13 [==============================] - 0s 3ms/step - loss: 0.4328 - accuracy: 0.8417
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4381 - accuracy: 0.8241
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4345 - accuracy: 0.8241
Epoch 10/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4283 - accuracy: 0.8392
Epoch 11

In [ ]:
#Example of prediction based on certain inputs. print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
inputvariable_test

array([[-0.21855296,  0.31710749, -0.14938447, ..., -0.14567981,
         0.11542304,  0.28378104],
       [-0.27141746,  1.44727832, -0.33290634, ..., -1.01213192,
        -0.56501333, -0.89282925],
       [-0.04604776, -0.84412512, -0.11098232, ..., -0.94337721,
        -0.77128156, -0.15687139],
       ...,
       [-0.13230036, -0.12253613, -0.14574637, ..., -0.1540065 ,
        -0.36319493,  0.31452423],
       [-0.24637638,  0.56799108, -0.28682376, ..., -0.27652787,
        -0.46515527, -0.90171062],
       [-1.35013142,  0.65639767, -1.34712739, ..., -0.40202307,
         0.30602931,  0.19496737]])

In [ ]:
predictios_from_testingset =  ArtificalNeuralNetworkModel.predict(inputvariable_test)

In [ ]:
predictios_from_testingset 

array([[0.90549684],
       [0.07791042],
       [0.14097694],
       [0.12900281],
       [0.20424154],
       [0.14288205],
       [0.26959962],
       [0.10032737],
       [0.04441005],
       [0.15572828],
       [0.846702  ],
       [0.1367014 ],
       [0.10876873],
       [0.23022202],
       [0.6724818 ],
       [0.9643012 ],
       [0.98043025],
       [0.57009   ],
       [0.78507674],
       [0.9849236 ],
       [0.88974446],
       [0.9399227 ],
       [0.34058046],
       [0.09577003],
       [0.89079416],
       [0.15074733],
       [0.0634532 ],
       [0.9867241 ],
       [0.11973315],
       [0.5101384 ],
       [0.08334634],
       [0.30509067],
       [0.27598172],
       [0.49159145],
       [0.06950304],
       [0.5770671 ],
       [0.11891744],
       [0.27531937],
       [0.1423622 ],
       [0.44103962],
       [0.15686801],
       [0.19099769],
       [0.14010155],
       [0.07663202],
       [0.4397586 ],
       [0.8699684 ],
       [0.04737768],
       [0.084

In [ ]:
Trueorfalsetesting=(predictios_from_testingset>0.50)
print(Trueorfalsetesting)
Trueorfalsetesting_dataframe = pd.DataFrame(Trueorfalsetesting)

[[ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 

In [ ]:
print(Trueorfalsetesting_dataframe)

         0
0     True
1    False
2    False
3    False
4    False
..     ...
166   True
167   True
168  False
169  False
170  False

[171 rows x 1 columns]
