<a href="https://colab.research.google.com/github/Sang897/data-analytics-projects/blob/master/PredictingusingAirlinedata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf



In [ ]:
#The purpose of this project is to utilize Artifical Neural Network to create ML that predicts different inputs of data to predict whether
#customer will give binary output anwer as "satisified" or "not satisfied"
#The following data is based on customer service data of Airline 
dataset = pd.read_csv('Customer Service Network2.csv')

In [ ]:
#Plan: Gender needs categorical encoding

In [ ]:
#What are the features that are valuable? 
#Gender, Customer Type, Age, Type of Travel, Class, Flight Distance, Inflight wifi service, Inflight Entertainment, On-board Service, 
#Baggage Handling, Checking Service, Cleainess, Deparatu  re delay in minutes, arrival delay in minutes 

#Which column should be used as an output? 
#Satisfaction column 

for col in dataset.columns:
  print(col)

#Is the result different if an array and a dataframe? 
#Tried using 
#numpy.ndarray but dataframe is the one that works? 

#Try using both dataframe and numpy.array version 

satisfaction
Gender
Customer Type
Age
Type of Travel
Class
Flight Distance
Seat comfort
Departure/Arrival time convenient
Food and drink
Gate location
Inflight wifi service
Inflight entertainment
Online support
Ease of Online booking
On-board service
Leg room service
Baggage handling
Checkin service
Cleanliness
Online boarding
Departure Delay in Minutes
Arrival Delay in Minutes


In [ ]:
dataset.dtypes

satisfaction                          object
Gender                                object
Customer Type                         object
Age                                    int64
Type of Travel                        object
Class                                 object
Flight Distance                        int64
Seat comfort                           int64
Departure/Arrival time convenient      int64
Food and drink                         int64
Gate location                          int64
Inflight wifi service                  int64
Inflight entertainment                 int64
Online support                         int64
Ease of Online booking                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Online boarding                        int64
Departure Delay in Minutes             int64
Arrival De

In [ ]:
dataset.columns

Index(['satisfaction', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes'],
      dtype='object')

In [ ]:
Inputvariable = dataset.iloc[:,[1,2,3,4,5,6]].values #the limitation of this project is that the rating inputs such as "ease of online booking",
#on-board service", "leg room service", "baggage handling" that has score of 0 to 5 was not utlized in the ML as input.
#The reason is that I noticed that when using it, this creates loss amount in the final training input as zero when the inputs are scales of 0 to 5. 
#I assume that this is because the scale itself is too low to compare. So I used following critical inputs: "Gender, "Customer Type", "Type of Travel",
#"Age", "Flight Distance" to make a prediction of whether the satisfication is yes or no. 

In [ ]:
print(Inputvariable)

[['Female' 'Loyal Customer' 65 'Personal Travel' 'Eco' 265]
 ['Male' 'Loyal Customer' 47 'Personal Travel' 'Business' 2464]
 ['Female' 'Loyal Customer' 15 'Personal Travel' 'Eco' 2138]
 ...
 ['Male' 'disloyal Customer' 69 'Personal Travel' 'Eco' 2320]
 ['Male' 'disloyal Customer' 66 'Personal Travel' 'Eco' 2450]
 ['Female' 'disloyal Customer' 38 'Personal Travel' 'Eco' 4307]]


In [ ]:
#Inputvariable.columns

In [ ]:
#Check: Gender, Customer Type, Age, Type of Travel, Class, Flight Distance, Inflight wifi service, Inflight Entertainment, On-board Service, 
#Baggage Handling, Checking Service, Cleainess, Deparature delay in minutes, arrival delay in minutes 
Inputvariable[1,:] #Compared with excel file and these are all correct. 
#For the inputs, Male or female requires label encoding, Loyal Customer requires label encoding, Personal Travel requires label encoding, and buissness requires hot encodin. 


array(['Male', 'Loyal Customer', 47, 'Personal Travel', 'Business', 2464],
      dtype=object)

In [ ]:
Outputvariable =dataset.iloc[:,0].values 

In [ ]:
Outputvariable

array(['satisfied', 'satisfied', 'satisfied', ..., 'dissatisfied',
       'dissatisfied', 'dissatisfied'], dtype=object)

In [ ]:
Outputvariable
#Perform encoding for binary result with relationship. 

from sklearn.preprocessing import LabelEncoder #Imports to binary result relationsihp 
Encoder = LabelEncoder()
Outputvariable = Encoder.fit_transform(Outputvariable) #trans

In [ ]:
 Outputvariable #Satisified = 1, dissatisified = 0 

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
Inputvariable[:,0] = Encoder.fit_transform(Inputvariable[:,0])
Inputvariable[:,0] #Male = 0, Female = 1 

array([0, 1, 0, ..., 1, 1, 0], dtype=object)

In [ ]:
Inputvariable[0,:]

array([0, 'Loyal Customer', 65, 'Personal Travel', 'Eco', 265],
      dtype=object)

In [ ]:
Inputvariable[:,1] = Encoder.fit_transform(Inputvariable[:,1])
Inputvariable[:,1]#Loyal customer  = 0 and disloyal customer = 1  



array([0, 0, 0, ..., 1, 1, 1], dtype=object)

In [ ]:
Inputvariable[0,:] #Personal travel requires label encoding 


array([0, 0, 65, 'Personal Travel', 'Eco', 265], dtype=object)

In [ ]:
Inputvariable[:,3] = Encoder.fit_transform(Inputvariable[:,3])
Inputvariable[:,3] 

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

In [ ]:
Inputvariable[0,:]

array([0, 0, 65, 1, 'Eco', 265], dtype=object)

In [ ]:
Inputvariable[0,:]

array([0, 0, 65, 1, 'Eco', 265], dtype=object)

In [ ]:
Inputvariable[1,:]

array([1, 0, 47, 1, 'Business', 2464], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
hotencoder= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
Inputvariable= np.array(hotencoder.fit_transform(Inputvariable))

In [ ]:
Inputvariable[0,:]
Inputvariable[1:]

array([[1.0, 0.0, 0.0, ..., 47, 1, 2464],
       [0.0, 1.0, 0.0, ..., 15, 1, 2138],
       [0.0, 1.0, 0.0, ..., 60, 1, 623],
       ...,
       [0.0, 1.0, 0.0, ..., 69, 1, 2320],
       [0.0, 1.0, 0.0, ..., 66, 1, 2450],
       [0.0, 1.0, 0.0, ..., 38, 1, 4307]], dtype=object)

In [ ]:
#Make training and testing set. 
from sklearn.model_selection import train_test_split
inputvariable_train, inputvariable_test, outputvariable_train, outputvariable_test = train_test_split(Inputvariable, Outputvariable, test_size = 0.3, random_state = 0)

In [ ]:
#Make features scaling for ML inputs. 
from sklearn.preprocessing import StandardScaler
Standardscaler = StandardScaler()
inputvariable_train = Standardscaler.fit_transform(inputvariable_train) #Applies features scaling for both train and test set to avoid information leakage. 
inputvariable_test = Standardscaler.transform(inputvariable_test) 

In [ ]:
inputvariable_test  

array([[-0.95526504, -0.90563601,  3.58302271, ...,  0.69930262,
        -0.67155633, -0.74517665],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  0.69930262,
        -0.67155633, -1.08459749],
       [ 1.0468299 , -0.90563601, -0.27909396, ..., -0.15980411,
        -0.67155633, -0.62325825],
       ...,
       [-0.95526504,  1.10419638, -0.27909396, ..., -1.81193243,
         1.48907837, -0.26725651],
       [-0.95526504, -0.90563601,  3.58302271, ...,  0.63321748,
         1.48907837, -0.38624887],
       [-0.95526504,  1.10419638, -0.27909396, ..., -0.02763384,
         1.48907837,  0.57739421]])

In [ ]:
#we are using ANN based on fully connected network, not a computational network. So we use squential classA
ArtificalNeuralNetworkfullyconnected= tf.keras.models.Sequential()


In [ ]:
#created as an instance of sequential class which initializes ANN as sequence of layers. 
#Dense class in tensorflow

#These are two hidden layers. 
ArtificalNeuralNetworkfullyconnected.add(tf.keras.layers.Dense(6, activation = 'relu'))
#call method inside sequential class. 
#created as an object of a dense class. So call the dense class. So
#we call the denser class from tensorflow keras library
#input neurons already have the #of hidden neurans. So this is for hidden layers for units for dense class. 
#And we use 6-8. 
#and module layers
ArtificalNeuralNetworkfullyconnected.add(tf.keras.layers.Dense(6, activation = 'relu'))


In [ ]:
#Now we have the output layer. 
ArtificalNeuralNetworkfullyconnected.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

#Output is a binary that takes 0 or 1 which is one neuron to get the final predictions. 
#if non binary that has 3 outputs of A B C, then we need 3 dimensions. 
# A = [1,0,0], B = [0,1,1], C=[0,0,1]
#sigmoid allows to get probability of binary outcome to find the probability that customer will make
#either satisified or not satisified. 


In [ ]:
ArtificalNeuralNetworkfullyconnected.compile(      
optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [ ]:
inputvariable_train


array([[-0.95526504, -0.90563601,  3.58302271, ..., -0.88674057,
         1.48907837, -0.38722422],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  0.43496209,
        -0.67155633,  1.62686784],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  0.43496209,
        -0.67155633,  1.94678173],
       ...,
       [-0.95526504,  1.10419638, -0.27909396, ...,  0.50104722,
        -0.67155633,  0.11312892],
       [-0.95526504,  1.10419638, -0.27909396, ..., -0.09371898,
        -0.67155633,  0.1375126 ],
       [ 1.0468299 , -0.90563601, -0.27909396, ..., -1.01891083,
        -0.67155633,  3.13085329]])

In [ ]:
outputvariable_train

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
ArtificalNeuralNetworkfullyconnected.fit(inputvariable_train, outputvariable_train, batch_size = 30, epochs = 100) 

Epoch 1/100
3031/3031 [==============================] - 6s 2ms/step - loss: 0.5162 - accuracy: 0.7601
Epoch 2/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4866 - accuracy: 0.7816
Epoch 3/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4856 - accuracy: 0.7826
Epoch 4/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4853 - accuracy: 0.7826
Epoch 5/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4850 - accuracy: 0.7834
Epoch 6/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4849 - accuracy: 0.7826
Epoch 7/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4846 - accuracy: 0.7838
Epoch 8/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4844 - accuracy: 0.7830
Epoch 9/100
3031/3031 [==============================] - 5s 2ms/step - loss: 0.4842 - accuracy: 0.7828
Epoch 10/100
3031/3031 [==============================] - 5s 2ms/step - l

In [ ]:
makeprediction =ArtificalNeuralNetworkfullyconnected.predict(inputvariable_test)

In [ ]:
makeprediction>0.5 

array([[ True],
       [False],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])