<a href="https://colab.research.google.com/github/Sang897/data-analytics-projects/blob/master/PredictingusingAirlinedata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#The following data is based on customer service data of Airline 
dataset = pd.read_csv('Customer Service Network.csv')

In [ ]:
#Plan: Gender needs categorical encoding
#Some of the require "label encoding" ex) gender 
#Some of them require "One hot encoding" ex) geogrpahy

In [ ]:
#What are the features that are valuable? 
#Gender, Customer Type, Age, Type of Travel, Class, Flight Distance, Inflight wifi service, Inflight Entertainment, On-board Service, 
#Baggage Handling, Checking Service, Cleainess, Deparatu  re delay in minutes, arrival delay in minutes 

#Which column should be used as an output? 
#Satisfaction column 

for col in dataset.columns:
  print(col)

#Is the result different if an array and a dataframe? 
#Tried using 
#numpy.ndarray but dataframe is the one that works? 

#Try using both dataframe and numpy.array version 

satisfaction
Gender
Customer Type
Age
Type of Travel
Class
Flight Distance
Seat comfort
Departure/Arrival time convenient
Food and drink
Gate location
Inflight wifi service
Inflight entertainment
Online support
Ease of Online booking
On-board service
Leg room service
Baggage handling
Checkin service
Cleanliness
Online boarding
Departure Delay in Minutes
Arrival Delay in Minutes


In [ ]:
dataset.dtypes

satisfaction                          object
Gender                                object
Customer Type                         object
Age                                    int64
Type of Travel                        object
Class                                 object
Flight Distance                        int64
Seat comfort                           int64
Departure/Arrival time convenient      int64
Food and drink                         int64
Gate location                          int64
Inflight wifi service                  int64
Inflight entertainment                 int64
Online support                         int64
Ease of Online booking                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Online boarding                        int64
Departure Delay in Minutes             int64
Arrival De

In [ ]:
dataset.columns

Index(['satisfaction', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Seat comfort',
       'Departure/Arrival time convenient', 'Food and drink', 'Gate location',
       'Inflight wifi service', 'Inflight entertainment', 'Online support',
       'Ease of Online booking', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness', 'Online boarding',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes'],
      dtype='object')

In [ ]:
Inputvariable = dataset.iloc[:,[1,2,3,4,5,6,11,12,15,17,18,19,-2,-1]].values

In [ ]:
print(Inputvariable)

[['Female' 'Loyal Customer' 65 ... 3 0 0.0]
 ['Male' 'Loyal Customer' 47 ... 3 310 305.0]
 ['Female' 'Loyal Customer' 15 ... 4 0 0.0]
 ...
 ['Male' 'disloyal Customer' 69 ... 3 155 163.0]
 ['Male' 'disloyal Customer' 66 ... 1 193 205.0]
 ['Female' 'disloyal Customer' 38 ... 3 185 186.0]]


In [ ]:
Inputvariable.columns

AttributeError: ignored

In [ ]:
#Check: Gender, Customer Type, Age, Type of Travel, Class, Flight Distance, Inflight wifi service, Inflight Entertainment, On-board Service, 
#Baggage Handling, Checking Service, Cleainess, Deparature delay in minutes, arrival delay in minutes 
Inputvariable[1,:] #Compared with excel file and these are all correct. 
#For the inputs, Male or female requires label encoding, Loyal Customer requires label encoding, Personal Travel requires label encoding, and buissness requires hot encodin. 


array(['Male', 'Loyal Customer', 47, 'Personal Travel', 'Business', 2464,
       0, 2, 4, 4, 2, 3, 310, 305.0], dtype=object)

In [ ]:
Outputvariable =dataset.iloc[:,0].values 

In [ ]:
Outputvariable

array(['satisfied', 'satisfied', 'satisfied', ..., 'dissatisfied',
       'dissatisfied', 'dissatisfied'], dtype=object)

In [ ]:
Outputvariable
#Perform encoding for binary result with relationship. 

from sklearn.preprocessing import LabelEncoder #Imports to binary result relationsihp 
Encoder = LabelEncoder()
Outputvariable = Encoder.fit_transform(Outputvariable) #trans

In [ ]:
 Outputvariable #Satisified = 1, dissatisified = 0 

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
Inputvariable[:,0] = Encoder.fit_transform(Inputvariable[:,0])
Inputvariable[:,0] #Male = 0, Female = 1 

array([0, 1, 0, ..., 1, 1, 0], dtype=object)

In [ ]:
Inputvariable[0,:]

array([0, 'Loyal Customer', 65, 'Personal Travel', 'Eco', 265, 2, 4, 3, 3,
       5, 3, 0, 0.0], dtype=object)

In [ ]:
Inputvariable[:,1] = Encoder.fit_transform(Inputvariable[:,1])
Inputvariable[:,1]#Loyal customer  = 0 and disloyal customer = 1 

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

In [ ]:
Inputvariable[0,:] #Personal travel requires label encoding 


array([0, 0, 65, 'Personal Travel', 'Eco', 265, 2, 4, 3, 3, 5, 3, 0, 0.0],
      dtype=object)

In [ ]:
Inputvariable[:,3] = Encoder.fit_transform(Inputvariable[:,3])
Inputvariable[:,3] #Personal Travel: 1 Business Travel: 0 

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

In [ ]:
Inputvariable[0,:]

array([0, 0, 65, 1, 'Eco', 265, 2, 4, 3, 3, 5, 3, 0, 0.0], dtype=object)

In [ ]:
Inputvariable[0,:]

array([0, 0, 65, 1, 'Eco', 265, 2, 4, 3, 3, 5, 3, 0, 0.0], dtype=object)

In [ ]:
Inputvariable[1,0:4]

array([1, 0, 47, 1], dtype=object)

In [ ]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [ ]:
hotencoder= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
Inputvariable= np.array(hotencoder.fit_transform(Inputvariable))

In [ ]:
#Make training and testing set. 
from sklearn.model_selection import train_test_split
inputvariable_train, inputvariable_test, outputvariable_train, outputvariable_test = train_test_split(Inputvariable, Outputvariable, test_size = 0.3, random_state = 0)

In [ ]:
outputvaraible_train,

(array([1, 0, 1, ..., 0, 0, 0]),)

In [ ]:
#Make features scaling for ML inputs. 
from sklearn.preprocessing import StandardScaler
Standardscaler = StandardScaler()
inputvariable_train = Standardscaler.fit_transform(inputvariable_train) #Applies features scaling for both train and test set to avoid information leakage. 
inputvariable_test = Standardscaler.transform(inputvariable_test) 

In [ ]:
inputvariable_test  

array([[-0.95526504, -0.90563601,  3.58302271, ..., -0.61273111,
        -0.38624069, -0.10613943],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  0.25539932,
        -0.38624069, -0.39258186],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  1.12352975,
        -0.38624069, -0.39258186],
       ...,
       [-0.95526504,  1.10419638, -0.27909396, ..., -0.61273111,
        -0.38624069, -0.39258186],
       [-0.95526504, -0.90563601,  3.58302271, ...,  0.25539932,
        -0.38624069, -0.26238076],
       [-0.95526504,  1.10419638, -0.27909396, ...,  0.25539932,
        -0.38624069, -0.39258186]])

In [ ]:
#we are using ANN based on fully connected network, not a computational network. So we use squential classA
ArtificalNeuralNetworkfullyconnected= tf.keras.models.Sequential()


In [ ]:
#created as an instance of sequential class which initializes ANN as sequence of layers. 
#Dense class in tensorflow

#These are two hidden layers. 
ArtificalNeuralNetworkfullyconnected.add(tf.keras.layers.Dense(6, activation = 'relu'))
#call method inside sequential class. 
#created as an object of a dense class. So call the dense class. So
#we call the denser class from tensorflow keras library
#input neurons already have the #of hidden neurans. So this is for hidden layers for units for dense class. 
#And we use 6-8. 
#and module layers
ArtificalNeuralNetworkfullyconnected.add(tf.keras.layers.Dense(6, activation = 'relu'))


In [ ]:
#Now we have the output layer. 
ArtificalNeuralNetworkfullyconnected.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

#Output is a binary that takes 0 or 1 which is one neuron to get the final predictions. 
#if non binary that has 3 outputs of A B C, then we need 3 dimensions. 
# A = [1,0,0], B = [0,1,1], C=[0,0,1]
#sigmoid allows to get probability of binary outcome to find the probability that customer will make
#either satisified or not satisified. 


In [ ]:
ArtificalNeuralNetworkfullyconnected.compile(      
optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [ ]:
inputvariable_train


array([[-0.95526504, -0.90563601,  3.58302271, ...,  0.25539932,
        -0.0178024 , -0.39258186],
       [ 1.0468299 , -0.90563601, -0.27909396, ..., -2.34899197,
        -0.30728963, -0.18426009],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  0.25539932,
        -0.38624069, -0.39258186],
       ...,
       [-0.95526504,  1.10419638, -0.27909396, ...,  0.25539932,
         0.27168483,  0.59694654],
       [-0.95526504,  1.10419638, -0.27909396, ..., -0.61273111,
        -0.38624069, -0.39258186],
       [ 1.0468299 , -0.90563601, -0.27909396, ...,  0.25539932,
        -0.25465559, -0.28842098]])

In [ ]:
outputvariable_train

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
ArtificalNeuralNetworkfullyconnected.fit(inputvariable_train, outputvariable_train, batch_size = 30, epochs = 10) 

Epoch 1/10
3031/3031 [==============================] - 7s 2ms/step - loss: nan - accuracy: 0.4535
Epoch 2/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 3/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 4/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 5/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 6/10
3031/3031 [==============================] - 15s 5ms/step - loss: nan - accuracy: 0.4533
Epoch 7/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 8/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 9/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533
Epoch 10/10
3031/3031 [==============================] - 6s 2ms/step - loss: nan - accuracy: 0.4533


In [ ]:
makeprediction =ArtificalNeuralNetworkfullyconnected.predict(inputvariable_test)

In [ ]:
makeprediction

array([[nan],
       [nan],
       [nan],
       ...,
       [nan],
       [nan],
       [nan]], dtype=float32)